<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ProductCategories as ModelsProductCategories;

class ProductCategoriesSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // ModelsProductCategories::create(['Name' => 'Despensa']);
        // ModelsProductCategories::create(['Name' => 'Bebidas']);
        // ModelsProductCategories::create(['Name' => 'Cervezas, Vinos y Licores']);
        // ModelsProductCategories::create(['Name' => 'Carnes, Aves y Pescados']);
        // ModelsProductCategories::create(['Name' => 'Frutas y Verduras']);
        // ModelsProductCategories::create(['Name' => 'Quesos']);
        // ModelsProductCategories::create(['Name' => 'Salchichoneria']);
        // ModelsProductCategories::create(['Name' => 'Gourmet']);
        // ModelsProductCategories::create(['Name' => 'Botanas']);
        // ModelsProductCategories::create(['Name' => 'Desechables']);
        // ModelsProductCategories::create(['Name' => 'Limpieza']);
        // ModelsProductCategories::create(['Name' => 'Aseo Personal']);
        // ModelsProductCategories::create(['Name' => 'Farmacia']);
        // ModelsProductCategories::create(['Name' => 'Tabaco y Vapeadores']);
        // ModelsProductCategories::create(['Name' => 'Lacteos y Huevo']);
        // ModelsProductCategories::create(['Name' => 'Panaderia']);
        // ModelsProductCategories::create(['Name' => 'Dulces']);
        // ModelsProductCategories::create(['Name' => 'Jugos, Bebidas y Aguas']);

        /*Departments Insert*/
        ModelsProductCategories::create(['Name' => 'SIN DEFINIR']);
        ModelsProductCategories::create(['Name' => 'ALIMENTOS']);
        ModelsProductCategories::create(['Name' => 'BEBIDAS']);
        ModelsProductCategories::create(['Name' => 'COMBOS']);
        ModelsProductCategories::create(['Name' => 'OTROS']);
        ModelsProductCategories::create(['Name' => 'ABARROTES']);
        ModelsProductCategories::create(['Name' => 'SEMILLAS']);
        ModelsProductCategories::create(['Name' => 'MULTISERVICIOS']);
        ModelsProductCategories::create(['Name' => 'LACTEOS']);
        ModelsProductCategories::create(['Name' => 'GOURMET']);
        ModelsProductCategories::create(['Name' => 'FRUTAS']);
        ModelsProductCategories::create(['Name' => 'CREMERIA']);
        ModelsProductCategories::create(['Name' => 'COMIDA']);
        ModelsProductCategories::create(['Name' => 'VERDURAS']);
        ModelsProductCategories::create(['Name' => 'SOLVENTES']);
        ModelsProductCategories::create(['Name' => 'MARISCOS']);
        ModelsProductCategories::create(['Name' => 'SOPA']);
        ModelsProductCategories::create(['Name' => 'ABARROTE']);
        ModelsProductCategories::create(['Name' => 'VELAS']);
        ModelsProductCategories::create(['Name' => 'PAPAS']);
        ModelsProductCategories::create(['Name' => 'CAFE']);
        ModelsProductCategories::create(['Name' => 'ACEITE']);
        ModelsProductCategories::create(['Name' => 'SALSA']);
        ModelsProductCategories::create(['Name' => 'BOTANA']);
        ModelsProductCategories::create(['Name' => 'LIMPIEZA']);
        ModelsProductCategories::create(['Name' => 'FRITURA']);
        ModelsProductCategories::create(['Name' => 'DESECHABLES']);
        ModelsProductCategories::create(['Name' => 'SALCHICHONERIA']);
        ModelsProductCategories::create(['Name' => 'BASICOS']);
        ModelsProductCategories::create(['Name' => 'cerveza']);
        ModelsProductCategories::create(['Name' => 'bebida']);
        ModelsProductCategories::create(['Name' => 'VINOS DE MESA']);
        ModelsProductCategories::create(['Name' => 'DESPENSA']);
        ModelsProductCategories::create(['Name' => 'CERVEZAS, VINOS Y LICORES']);
        ModelsProductCategories::create(['Name' => 'TABACO']);
        ModelsProductCategories::create(['Name' => 'BEBIDAS Y JUGOS']);
        ModelsProductCategories::create(['Name' => 'JUGOS Y AGUAS']);
        ModelsProductCategories::create(['Name' => 'BOTANAS']);
        ModelsProductCategories::create(['Name' => 'PANADERIA']);
        ModelsProductCategories::create(['Name' => 'FRUTAS Y VERDURAS']);
        ModelsProductCategories::create(['Name' => 'DULCES']);
        ModelsProductCategories::create(['Name' => 'FERRETERIA Y JARDINERIA']);
        ModelsProductCategories::create(['Name' => 'CARNES, AVES Y PESCADOS']);
        ModelsProductCategories::create(['Name' => 'LACTEOS Y HUEVO']);
        ModelsProductCategories::create(['Name' => 'QUESOS']);
        ModelsProductCategories::create(['Name' => 'QUESO']);


        /*Categories Insert*/
        ModelsProductCategories::create(['Name' => 'SIN DEFINIR', 'ParentId' => 1]);
        ModelsProductCategories::create(['Name' => 'DESAYUNOS', 'ParentId' => 2]);
        ModelsProductCategories::create(['Name' => 'COMIDAS', 'ParentId' => 2]);
        ModelsProductCategories::create(['Name' => 'CENAS', 'ParentId' => 2]);
        ModelsProductCategories::create(['Name' => 'POSTRES', 'ParentId' => 2]);
        ModelsProductCategories::create(['Name' => 'AGUAS', 'ParentId' => 3]);
        ModelsProductCategories::create(['Name' => 'JUGOS', 'ParentId' => 3]);
        ModelsProductCategories::create(['Name' => 'REFRESCOS', 'ParentId' => 3]);
        ModelsProductCategories::create(['Name' => 'CERVEZAS', 'ParentId' => 3]);
        ModelsProductCategories::create(['Name' => 'VINOS', 'ParentId' => 3]);
        ModelsProductCategories::create(['Name' => 'LICORES', 'ParentId' => 3]);
        ModelsProductCategories::create(['Name' => 'COMBOS', 'ParentId' => 4]);
        ModelsProductCategories::create(['Name' => 'ENDULZANTE', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'DULCES', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'PAGO DE SERVICIOS', 'ParentId' => 8]);
        ModelsProductCategories::create(['Name' => 'RECARGAS', 'ParentId' => 8]);
        ModelsProductCategories::create(['Name' => 'CEREALES', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'LECHE', 'ParentId' => 9]);
        ModelsProductCategories::create(['Name' => 'ESPECIAS', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'SALSAS', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'SANTA CLARA', 'ParentId' => 9]);
        ModelsProductCategories::create(['Name' => 'VERDURAS', 'ParentId' => 11]);
        ModelsProductCategories::create(['Name' => 'QUESOS', 'ParentId' => 12]);
        ModelsProductCategories::create(['Name' => 'PAPAS', 'ParentId' => 13]);
        ModelsProductCategories::create(['Name' => 'LACTEOS', 'ParentId' => 12]);
        ModelsProductCategories::create(['Name' => 'PAN', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'LATAS', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'TABACO', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'CARNES', 'ParentId' => 13]);
        ModelsProductCategories::create(['Name' => 'HIERBAS', 'ParentId' => 14]);
        ModelsProductCategories::create(['Name' => 'SEMILLAS', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'PESCADOS', 'ParentId' => 16]);
        ModelsProductCategories::create(['Name' => 'HARINAS', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'CREMERIA', 'ParentId' => 12]);
        ModelsProductCategories::create(['Name' => 'platano morado', 'ParentId' => 11]);
        ModelsProductCategories::create(['Name' => 'Lima', 'ParentId' => 11]);
        ModelsProductCategories::create(['Name' => 'Lima', 'ParentId' => 14]);
        ModelsProductCategories::create(['Name' => 'Lim', 'ParentId' => 11]);
        ModelsProductCategories::create(['Name' => 'FRUTAS', 'ParentId' => 11]);
        ModelsProductCategories::create(['Name' => 'ABARROTE', 'ParentId' => 17]);
        ModelsProductCategories::create(['Name' => 'ABARROTES', 'ParentId' => 19]);
        ModelsProductCategories::create(['Name' => 'GOURMET', 'ParentId' => 21]);
        ModelsProductCategories::create(['Name' => 'ACEITE', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'GALLETA', 'ParentId' => 18]);
        ModelsProductCategories::create(['Name' => 'JAMON', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'LIMPIADORES', 'ParentId' => 18]);
        ModelsProductCategories::create(['Name' => 'BOLSA', 'ParentId' => 18]);
        ModelsProductCategories::create(['Name' => 'CAFE', 'ParentId' => 18]);
        ModelsProductCategories::create(['Name' => 'SALSA', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'SERVILLETAS', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'bebidas', 'ParentId' => 18]);
        ModelsProductCategories::create(['Name' => 'DESINFECTANTE', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'BOTANA', 'ParentId' => 24]);
        ModelsProductCategories::create(['Name' => 'JABÓN PARA ROPA', 'ParentId' => 25]);
        ModelsProductCategories::create(['Name' => 'TE', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'DESECHABLES', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'FRITURAS', 'ParentId' => 24]);
        ModelsProductCategories::create(['Name' => 'PLÁSTICO', 'ParentId' => 27]);
        ModelsProductCategories::create(['Name' => 'LIMPIADOR DE PISO', 'ParentId' => 25]);
        ModelsProductCategories::create(['Name' => 'ENLATADOS', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'CHORIZO', 'ParentId' => 28]);
        ModelsProductCategories::create(['Name' => 'SALCHICHA', 'ParentId' => 28]);
        ModelsProductCategories::create(['Name' => 'JAMÓN', 'ParentId' => 28]);
        ModelsProductCategories::create(['Name' => 'TOCINO', 'ParentId' => 28]);
        ModelsProductCategories::create(['Name' => 'ABARROTE', 'ParentId' => 29]);
        ModelsProductCategories::create(['Name' => 'BOLSAS', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'cerveza', 'ParentId' => 31]);
        ModelsProductCategories::create(['Name' => 'LICOR', 'ParentId' => 31]);
        ModelsProductCategories::create(['Name' => 'JUGOS', 'ParentId' => 18]);
        ModelsProductCategories::create(['Name' => 'VINO', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'AGUA', 'ParentId' => 31]);
        ModelsProductCategories::create(['Name' => 'VINO BLANCO', 'ParentId' => 32]);
        ModelsProductCategories::create(['Name' => 'VINO TINTO', 'ParentId' => 32]);
        ModelsProductCategories::create(['Name' => 'VINO BLANCO ESPUMOSO', 'ParentId' => 32]);
        ModelsProductCategories::create(['Name' => 'ESPECIAS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'ACEITES', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'CONSERVAS', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'VINO BLANCO', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'VINO TINTO', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'VINO BLANCO ESPUMOSO', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'VINO ROSADO', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'VINO BLACO ESPUMOSO', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'VINO TINTO ESPUMOSO', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'POR DEFINIR', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'VINO ESPUMOSO', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'ACEITES OLIVA, COMESTIBLES Y VINAGRE', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'CIGARROS', 'ParentId' => 35]);
        ModelsProductCategories::create(['Name' => 'CERVEZA', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'HARD SELTZER', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'REFRESCOS', 'ParentId' => 36]);
        ModelsProductCategories::create(['Name' => 'GELATINA, FRUTAS EN ALMIBAR', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'REFRESCOS', 'ParentId' => 31]);
        ModelsProductCategories::create(['Name' => 'REFRESCO', 'ParentId' => 36]);
        ModelsProductCategories::create(['Name' => 'VINAGRE BALSAMICO', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'PASTA', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'ESPECIAS', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'ENLATADOS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'CONSERVAS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'MAYONESA, MOSTAZA Y ADEREZOS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'SALSA', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'MIEL, CAJETA, MERMELADA', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'VINAGRE', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'COGNAC', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'SIDRA', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'CREMA BATDA', 'ParentId' => 9]);
        ModelsProductCategories::create(['Name' => 'TEQUILA', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'AGUA', 'ParentId' => 37]);
        ModelsProductCategories::create(['Name' => 'SEMILLAS', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'HIDRATANTE', 'ParentId' => 3]);
        ModelsProductCategories::create(['Name' => 'PALOMITAS', 'ParentId' => 38]);
        ModelsProductCategories::create(['Name' => 'QUESO', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'PAPAS', 'ParentId' => 24]);
        ModelsProductCategories::create(['Name' => 'GALLETAS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'TE,CAFÉ,SUSTITUTOS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'TE, CAFÉ, SUSTITUTOS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'CUCHARA', 'ParentId' => 27]);
        ModelsProductCategories::create(['Name' => 'POSTRES', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'PAN DULCE', 'ParentId' => 39]);
        ModelsProductCategories::create(['Name' => 'CEREAL, AVENA,GRANOLA', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'FRUTA', 'ParentId' => 40]);
        ModelsProductCategories::create(['Name' => 'VERDURA', 'ParentId' => 40]);
        ModelsProductCategories::create(['Name' => 'VASOS', 'ParentId' => 27]);
        ModelsProductCategories::create(['Name' => 'AZUCAR Y ENDULZANTES', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'TORTILLAS, PAN DE CAJA, TOSTADAS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'DIGESTIVOS Y CREMAS', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'GOMA DE MASCAR', 'ParentId' => 41]);
        ModelsProductCategories::create(['Name' => 'RON', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'PASTA', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'MEZCAL', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'PLATOS', 'ParentId' => 27]);
        ModelsProductCategories::create(['Name' => 'PANADERIA', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'MIEL, CAJETA, MERMELADA', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'LIMPIADORES MULTIUSOS', 'ParentId' => 25]);
        ModelsProductCategories::create(['Name' => 'JUGOS', 'ParentId' => 37]);
        ModelsProductCategories::create(['Name' => 'GALLETA', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'LANZA DE MADERA', 'ParentId' => 27]);
        ModelsProductCategories::create(['Name' => 'CONSOME, PURE Y CALDILLOS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'PEGAMENTOS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'AGUAS', 'ParentId' => 37]);
        ModelsProductCategories::create(['Name' => 'VELAS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'ENDULZANTE', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'PAPEL', 'ParentId' => 27]);
        ModelsProductCategories::create(['Name' => 'GLOBOS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'FIBRA', 'ParentId' => 25]);
        ModelsProductCategories::create(['Name' => 'PAN DULCE', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'CONSOMES, PURE Y CALDILLOS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'CHOCOLATE', 'ParentId' => 41]);
        ModelsProductCategories::create(['Name' => 'ENVASE', 'ParentId' => 37]);
        ModelsProductCategories::create(['Name' => 'PALOMITAS', 'ParentId' => 24]);
        ModelsProductCategories::create(['Name' => 'SALSA', 'ParentId' => 24]);
        ModelsProductCategories::create(['Name' => 'ALIMENTO', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'ACEITES OLIVA, COMESTIBLES Y VINAGRE', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'ACEITES OLIVA, COMESTIBLES Y VINAGRE', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'GOURMET', 'ParentId' => 3]);
        ModelsProductCategories::create(['Name' => 'AGUA MINERAL', 'ParentId' => 3]);
        ModelsProductCategories::create(['Name' => 'GOURMET', 'ParentId' => 37]);
        ModelsProductCategories::create(['Name' => 'AGUA MINERAL', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'VERDURAS', 'ParentId' => 40]);
        ModelsProductCategories::create(['Name' => 'HIERBAS', 'ParentId' => 40]);
        ModelsProductCategories::create(['Name' => 'ALCOHOL SOLIDO', 'ParentId' => 42]);
        ModelsProductCategories::create(['Name' => 'ALITA', 'ParentId' => 43]);
        ModelsProductCategories::create(['Name' => 'CEREAL, AVENA,GRANOLA', 'ParentId' => 6]);
        ModelsProductCategories::create(['Name' => 'SEMILLAS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'BEBIDA ENERGETICA', 'ParentId' => 3]);
        ModelsProductCategories::create(['Name' => 'DIGESTIVOS Y CREMAS', 'ParentId' => 3]);
        ModelsProductCategories::create(['Name' => 'TE', 'ParentId' => 3]);
        ModelsProductCategories::create(['Name' => 'GOMITAS', 'ParentId' => 41]);
        ModelsProductCategories::create(['Name' => 'CARNES', 'ParentId' => 43]);
        ModelsProductCategories::create(['Name' => 'SOPA Y PASTA', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'HARINA, ARROZ', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'HARINA, ARROZ', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'ATUN', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'ATUN', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'AZUCAR Y ENDULZANTE', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'BAGUETTE', 'ParentId' => 39]);
        ModelsProductCategories::create(['Name' => 'LICOR', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'PAN DULCE, GALLETAS, BARRAS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'GINEBRA', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'FRUTAS', 'ParentId' => 40]);
        ModelsProductCategories::create(['Name' => 'POLLO', 'ParentId' => 43]);
        ModelsProductCategories::create(['Name' => 'BRANDY', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'WHISKY', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'CACAHUATE', 'ParentId' => 24]);
        ModelsProductCategories::create(['Name' => 'TE, CAFÉ,SUSTITUTOS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'TE, CAFÉ,SUSTITUTOS', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'CREMA', 'ParentId' => 37]);
        ModelsProductCategories::create(['Name' => 'LECHE', 'ParentId' => 44]);
        ModelsProductCategories::create(['Name' => 'CALDO DE PAVO', 'ParentId' => 43]);
        ModelsProductCategories::create(['Name' => 'CARBON', 'ParentId' => 42]);
        ModelsProductCategories::create(['Name' => 'LECHE', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'CERILLOS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'SALSAS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'CHAMPAGNE', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'PAN', 'ParentId' => 39]);
        ModelsProductCategories::create(['Name' => 'CHAROLAS', 'ParentId' => 27]);
        ModelsProductCategories::create(['Name' => 'CHILES SECOS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'EMBUTIDO', 'ParentId' => 28]);
        ModelsProductCategories::create(['Name' => 'CHOCOLATE', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'AGUA MINERAL', 'ParentId' => 37]);
        ModelsProductCategories::create(['Name' => 'HIERBA', 'ParentId' => 40]);
        ModelsProductCategories::create(['Name' => 'FRUTAS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'JUGO', 'ParentId' => 37]);
        ModelsProductCategories::create(['Name' => 'LIMPIADORES', 'ParentId' => 25]);
        ModelsProductCategories::create(['Name' => 'CACAHUATES', 'ParentId' => 24]);
        ModelsProductCategories::create(['Name' => 'DULCES', 'ParentId' => 41]);
        ModelsProductCategories::create(['Name' => 'LICORES', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'DIP', 'ParentId' => 24]);
        ModelsProductCategories::create(['Name' => 'DESINFECTANTE', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'ENCENDEDOR', 'ParentId' => 35]);
        ModelsProductCategories::create(['Name' => 'HARINAS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'AGUA', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'PESCADOS', 'ParentId' => 43]);
        ModelsProductCategories::create(['Name' => 'PAN DULCE, GALLETAS, BARRAS', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'BEBIDA REHIDRATANTE', 'ParentId' => 3]);
        ModelsProductCategories::create(['Name' => 'ALIMENTO BEBES', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'DULCES', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'PASTILLAS', 'ParentId' => 41]);
        ModelsProductCategories::create(['Name' => 'HAMBURGUESA', 'ParentId' => 43]);
        ModelsProductCategories::create(['Name' => 'CERVEZAS', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'HIELO', 'ParentId' => 37]);
        ModelsProductCategories::create(['Name' => 'HUEVO', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'HIERBAS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'PRODUCTO SALUDABLE', 'ParentId' => 3]);
        ModelsProductCategories::create(['Name' => 'PRODUCTO SALUDABLE', 'ParentId' => 18]);
        ModelsProductCategories::create(['Name' => 'SOPA Y PASTA', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'QUESOS', 'ParentId' => 45]);
        ModelsProductCategories::create(['Name' => 'LACTEOS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'PRODUCTO SALUDABLE', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'LICOR', 'ParentId' => 3]);
        ModelsProductCategories::create(['Name' => 'GOURMET', 'ParentId' => 41]);
        ModelsProductCategories::create(['Name' => 'AZUCAR Y ENDULZANTE', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'DULCES', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'PRODUCTO SALUDABLE', 'ParentId' => 12]);
        ModelsProductCategories::create(['Name' => 'PESCADO', 'ParentId' => 43]);
        ModelsProductCategories::create(['Name' => 'PAVO', 'ParentId' => 43]);
        ModelsProductCategories::create(['Name' => 'MAYONESA, MOSTAZA Y ADEREZOS', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'PALETA', 'ParentId' => 41]);
        ModelsProductCategories::create(['Name' => 'PALILLOS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'AGUA TONICA', 'ParentId' => 37]);
        ModelsProductCategories::create(['Name' => 'PEPITAS', 'ParentId' => 24]);
        ModelsProductCategories::create(['Name' => 'PLATO', 'ParentId' => 27]);
        ModelsProductCategories::create(['Name' => 'QUESOS', 'ParentId' => 46]);
        ModelsProductCategories::create(['Name' => 'MULTIUSOS', 'ParentId' => 42]);
        ModelsProductCategories::create(['Name' => 'PRODUCTO SALUDABLE', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'LIMPIADORES', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'SANGRITA', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'SERVILLETAS', 'ParentId' => 27]);
        ModelsProductCategories::create(['Name' => 'VODKA', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'TE, CAFÉ, SUSTITUTOS', 'ParentId' => 10]);
        ModelsProductCategories::create(['Name' => 'TENEDOR', 'ParentId' => 27]);
        ModelsProductCategories::create(['Name' => 'PURE, CONSOME', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'ESPECIAS', 'ParentId' => 40]);
        ModelsProductCategories::create(['Name' => 'WHISKEY', 'ParentId' => 34]);
        ModelsProductCategories::create(['Name' => 'YOGHURT', 'ParentId' => 9]);
        ModelsProductCategories::create(['Name' => 'BOLSAS', 'ParentId' => 33]);
        ModelsProductCategories::create(['Name' => 'BOLSA', 'ParentId' => 33]);
    }
}
